config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#landing"
  get '/404', to: 'pages#not_found', as: 'not_found'

  # uncomment this if you use custom controller in /controllers/users
  # devise_for :users, controllers: {
  #   confirmations: 'users/confirmations',
  #   passwords: 'users/passwords',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   unlocks: 'users/unlocks',
  # }
  devise_for :users
  
  resources :folders, except: [:show] do
    resources :snippets, only: [:index, :new, :create]
  end

  resources :snippets, only: [:edit, :update, :destroy] do
    resources :versions, only: :index
  end

  get '/snippets/:id/file', to: 'snippets#download', as: 'download' 
  get '/snippets/:id/embed', to: 'snippets#embed', as: 'embed' 
  get '/embed/script', to: 'snippets#embed_script' 
  get '/embed/style', to: 'snippets#embed_style' 
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :snippets, dependent: :destroy

  enum status: [ :public, :private ], _prefix: 'is'

  validates :name, presence: true, length: {minimum: 2}
  validates :description, presence: false
  validates :status, presence: true

  scope :on_public, -> { where(status: :public) }
  scope :on_private, -> { where(status: :private) }
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  authorize_resource
  layout 'dashboard'

  # no show
  # index only show the list of folder
  def index
    @folders = Folder.accessible_by(current_ability)
  end

  def new
    @folders = Folder.accessible_by(current_ability)
    @folder = @folders.new
  end

  def create
    @folder = Folder.accessible_by(current_ability).new(folder_params)

    if @folder.save
      redirect_to folder_snippets_path(@folder)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @folders = Folder.accessible_by(current_ability)
    @folder = @folders.find(params[:id])
  end

  def update
    @folder = Folder.accessible_by(current_ability).find(params[:id])

    if @folder.update(folder_params)
      redirect_to folder_snippets_path(@folder)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @folder = Folder.accessible_by(current_ability).find(params[:id])
    @folder.destroy
    
    if @folders.exists?
      redirect_to folder_snippets_path(@folders.first), status: :see_other
    else
      redirect_to folders_path, status: :see_other
    end
  end

  private
  def folder_params
    params.require(:folder).permit(:name, :description, :status)
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_folder_lists.html.erb
<ul>
  <% @folders.each do |folder| %>
    <% unless folder.id.nil? %>
      <li class="hover:bg-gray-200">
      <%= link_to folder_snippets_path(folder), class: 'flex items-center p-4 border-b border-gray-400' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
        </svg>
        <p><%= folder.name %></p>
        <% if folder.is_private? %>
          <span class="ml-2 text-sm text-gray-500 p-1">private</span>
        <% end %>
      <% end %>
      </li>
    <% end %>
  <% end %>

  <% if can?(:create, @folders.klass) && !locals[:new_button_hide?] %>
    <li class="hover:bg-gray-200">
      <%= link_to new_folder_path, class: 'flex items-center p-4 border-b border-gray-400' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
        </svg>
        <p class="">Create Folder</p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/folders/edit.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {} %>
<% end %>

<% content_for :main_header do %> 
  <div class="p-4 border-b">
    <div>
      <h2 class="text-3xl font-bold mb-2">
        Edit <%= @folder.name %>
      </h2>
      <p class="text-lg mb-1">
      <% if current_user.folders.exists? %>
        <%= link_to 'go back', folder_snippets_path(@folder), class: 'text-red-700 underline' %> 
      <% else %>
        <%= link_to 'go back', folders_path, class: 'text-red-700 underline' %> 
      <% end %>
      </p>
    </div>
  </div>
<% end %>

<% content_for :main_content do %>
  <%= form_with class: 'mb-2', model:  @folder do |form| %>
    <div class="flex flex-col border p-4 rounded">
      <div class="mb-2">
        <div class="flex items-center">
          <%= form.label :name, 'Folder Name', class: 'text-gray-500 mr-2' %>
          <%= form.text_field :name, class: 'border-b' %>
        </div>
        <% @folder.errors.full_messages_for(:name).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :description, class: 'hidden' %>
        <%= form.text_area :description, class: 'w-full border p-2', placeholder: 'File Description' %>
        <% @folder.errors.full_messages_for(:description).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>
    
      <div class="mb-4">
        <%= form.label :status, class: 'text-gray-500' %>
        <%= form.select :status, ['public', 'private'], class: 'p-2 rounded' %>
      </div>

      <%= form.submit class: 'bg-green-400 rounded px-2 py-1 text-sm text-white self-end' %>
    </div>
  <% end %>
<% end %>

app/views/folders/index.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {} %>
<% end %>

<% content_for :main_header do %> 
  <div class="p-4 border-b">
    <div>
      <h2 class="text-3xl font-bold mb-2">Hello <%= current_user.username %>!</h2>
    </div>
  </div>
<% end %>

<% content_for :main_content do %>
  <% if current_user.folders.empty? %>
    <div class="p-6 flex flex-col items-center">
      <%= image_tag 'no_folders_found.png', class: "w-52 mb-4" %>
      <p>
        you don't have any folder, you 
    <%= link_to 'can create new folder', new_folder_path, class: 'text-red-700 underline' %>
      </p>
    </div>
  <% else %>
    <div class="p-6 flex flex-col items-center">
      <%= image_tag 'folders_neutral_state.png', class: "w-52 mb-4" %>
      <p>
        You can select your folder or you 
        <%= link_to 'can create new folder', new_folder_path, class: 'text-red-700 underline' %>
        to manage your snippets
      </p>
    </div>
  <% end %>
<% end %>

app/views/folders/new.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {new_button_hide?: true} %>
<% end %>

<% content_for :main_header do %> 
  <div class="p-4 border-b">
    <div>
      <h2 class="text-3xl font-bold mb-2">Create New Folder</h2>
      <p class="text-lg mb-1">
      <% if current_user.folders.exists? %>
        <%= link_to 'go back', folder_snippets_path(current_user.folders.first), class: 'text-red-700 underline' %> 
      <% else %>
        <%= link_to 'go back', folders_path, class: 'text-red-700 underline' %> 
      <% end %>
      </p>
    </div>
  </div>
<% end %>

<% content_for :main_content do %>
  <%= form_with class: 'mb-2', model:  @folder do |form| %>
    <div class="flex flex-col border p-4 rounded">
      <div class="field flex flex-col mb-4">
        <div class="flex items-center">
          <%= form.label :name, 'Folder Name', class: 'text-gray-500 mr-2' %>
          <%= form.text_field :name, class: 'p-1 rounded border-b'%>
        </div>
        <% @folder.errors.full_messages_for(:name).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :description, class: 'hidden' %>
        <%= form.text_area :description, class: 'w-full border p-2', placeholder: 'File Description' %>
        <% @folder.errors.full_messages_for(:description).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :status, class: 'text-gray-500' %>
        <%= form.select :status, ['public', 'private'], class: 'p-2 rounded' %>
      </div>
    
      <%= form.submit class: 'bg-green-400 rounded px-2 py-1 text-sm text-white self-end' %>
    </div>
  <% end %>
<% end %>