config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#landing"
  get '/404', to: 'pages#not_found', as: 'not_found'

  # uncomment this if you use custom controller in /controllers/users
  # devise_for :users, controllers: {
  #   confirmations: 'users/confirmations',
  #   passwords: 'users/passwords',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   unlocks: 'users/unlocks',
  # }
  devise_for :users
  
  resources :folders, except: [:show] do
    resources :snippets, only: [:index, :new, :create]
  end

  resources :snippets, only: [:edit, :update, :destroy] do
    resources :versions, only: :index
  end

  get '/snippets/:id/file', to: 'snippets#download', as: 'download' 
  get '/snippets/:id/embed', to: 'snippets#embed', as: 'embed' 
  get '/embed/script', to: 'snippets#embed_script' 
  get '/embed/style', to: 'snippets#embed_style' 
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  has_many :versions, dependent: :destroy
  belongs_to :user
  belongs_to :folder

  validates :name, presence: true, length: {minimum: 2}
  validates :content, presence: true
  validates :format, presence: false
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  authorize_resource except: [:embed_style, :embed_script]
  layout "dashboard"
  protect_from_forgery except: [:download, :embed, :embed_style, :embed_script]
  
  # no show, instead use versions index
  def index
    @folders = Folder.accessible_by(current_ability)
    @current_folder = Folder.find(params[:folder_id])
    @snippets = @current_folder.snippets
  end

  def new
    @folders = Folder.accessible_by(current_ability)
    @folder = @folders.find(params[:folder_id])
    @snippet = @folder.snippets.new
  end

  def create
    @folder = Folder.accessible_by(current_ability).find(params[:folder_id])
    @snippet = @folder.snippets.new(snippet_params)
    @snippet.user_id = current_user.id
    unless @snippet.name[0] == '.'
      @snippet.format = @snippet.name.split('.').reject do |str|
        str.empty?
      end.last
    end

    if @snippet.save
      redirect_to folder_snippets_path(@folder)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @folders = Folder.accessible_by(current_ability)
    @snippet = Snippet.accessible_by(current_ability).find(params[:id])
  end

  def update
    @snippet = Snippet.accessible_by(current_ability).find(params[:id])
    @old_snippet_content = @snippet.content

    unless @snippet.name[0] == '.'
      @snippet.format = @snippet.name.split('.').reject do |str|
        str.empty?
      end.last
    end

    if @snippet.update(snippet_params)
      unless @snippet.name[0] == '.'
        format = @snippet.name.split('.').reject do |str|
          str.empty?
        end.last
        @snippet.update(format: format)
      end

      if !@old_snippet_content.eql? @snippet.content
        @snippet.versions.create(
          old: @old_snippet_content, 
          new: @snippet.content
        )
      end

      redirect_to folder_snippets_path(@snippet.folder)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @snippet = Snippet.accessible_by(current_ability).find(params[:id])
    @snippet.destroy

    redirect_to folder_snippets_path(@snippet.folder), status: :see_other
  end

  def download
    @snippet = Snippet.accessible_by(current_ability).find(params[:id])
    send_data @snippet.content, :filename => @snippet.name
  end

  def embed
    @snippet = Snippet.accessible_by(current_ability).find(params[:id])
    
    render 'snippets/embed', handlers: :erb, formats: :js
  end

  def embed_script
    render file: "#{Rails.root}/app/javascript/embed.js", content_type: 'text/javascript;charset=UTF-8'
  end

  def embed_style
    render file: "#{Rails.root}/app/assets/stylesheets/embed.css", content_type: 'text/css;charset=UTF-8'
  end

  private
  def snippet_params
    params.require(:snippet).permit(:name, :content)
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/edit.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {} %>
<% end %>

<% content_for :main_header do %> 
  <div class="p-4 border-b">
    <div>
      <h2 class="text-3xl font-bold mb-2">
        Edit <%= "#{@snippet.name}" %>
      </h2>
      <p class="text-lg mb-1">
        go back to 
        <%= link_to @snippet.folder.name, folder_snippets_path(@snippet.folder), class: 'text-red-700 underline' %> 
        folder
      </p>
    </div>
  </div>
<% end %>

<% content_for :main_content do %>
  <%= form_with model: @snippet do |form| %>
    <div class="flex flex-col border p-4 rounded">
      <div class="mb-2">
        <div class="flex items-center">
          <%= form.label :name, 'Snippet Name', class: 'text-gray-500 mr-2' %>
          <%= form.text_field :name, id: 'name-input', class: 'border-b' %>
        </div>
        <% @snippet.errors.full_messages_for(:name).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :content, class: 'hidden' %>
        <%# EDITOR %>
        <div id="editor" class="relative">
          <%= form.text_area :content, class: 'resize-none w-full overflow-hidden pl-16 p-5 text-white', style: 'font-family: "Andale Mono"; background: rgb(20, 20, 20); min-height: 200px', id: 'snippet-input', placeholder: 'Input your code here' %>
          <pre class="w-full h-full absolute rounded line-numbers top-0 left-0 pb-0 opacity-90" style="position:absolute; pointer-events: none; margin: 0; white-space: pre-wrap;">
            <code id="snippet-overlay" class=""></code>
          </pre>
        </div>
        <% @snippet.errors.full_messages_for(:content).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>
    
      <%= form.submit class: 'bg-green-400 rounded px-2 py-1 text-sm text-white self-end' %>
  <% end %>
<% end %>

<%= content_for :additional_js do %>
  <% if controller_name == 'snippets' && action_name == 'edit' %>
    <%= javascript_include_tag "snippet-editor" %>
  <% end %>
<% end %>

app/views/snippets/embed.js.erb
(function () {
  const prismScriptIsExist = document.querySelector('#prism-script');
  const snippetTemplate = `
  <div class='symbolic-snippet-wrapper'>
    <pre class='line-numbers'>
      <code class='language-<%= @snippet.format %>'><%= raw @snippet.content.gsub '`', '\\\`' %></code>
    </pre>
    <p>
      <b><%= @snippet.name %></b>
      <span>
        created using <span>Symbolic Snippet</span>
      </span>
    </p>
  </div>
  `;

  if (!prismScriptIsExist) {
    document.write(`<link id="prism-style" rel="stylesheet" href="http://127.0.0.1:3000/embed/style">`)
    document.write(`<script id="prism-script" src="http://127.0.0.1:3000/embed/script"></script>`)
  }

  document.write(snippetTemplate);
})();

app/views/snippets/index.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {} %>
<% end %>

<% content_for :main_header do %> 
  <div class="flex p-4 border-b items-center justify-between">
    <div>
      <div class="flex">
        <h2 class="text-3xl font-bold mb-2 mr-2">
          <%= @current_folder.name %>
        </h2>
        <div class="flex">
          <% if can? :edit, @current_folder %>
            <%= link_to edit_folder_path(@current_folder), class: 'flex items-center mr-2' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1 stroke-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
              <p class="text-sm text-gray-600">Edit</p>
            <% end %>
          <% end %>
          <% if can? :destroy, @current_folder %>
            <%= link_to folder_path(@current_folder), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure to delete #{@current_folder.name} folder"
            }, class: 'flex items-center' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1 stroke-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
              </svg>
              <p class="text-sm text-gray-600">delete</p>
            <% end %>
          <% end %>
        </div>
      </div>
      <p class="text-lg mb-1"><%= @current_folder.description %></p>
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 stroke-gray-400" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <p class="text-sm text-gray-700"><%= @current_folder.created_at.strftime("%B %d, %Y") %></p>
        <% if @current_folder.is_private? %>
          <span class="p-1 rounded text-gray-700 bg-gray-200 text-sm ml-2">private</span>
        <% end %>
      </div>
    </div>
    <% if can? :create, @current_folder.snippets.klass %>
      <%= link_to new_folder_snippet_path, class: 'rounded-md bg-green-600 text-white flex items-center p-2' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 stroke-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <p>Create New Snippet</p>
      <% end %>
    <% end %>
  </div>
<% end %>

<% content_for :main_content do %>
  <% if @snippets.empty? %>
    <div class="p-6 flex flex-col items-center">
      <%= image_tag 'folders_empty.png', class: "w-52 mb-4" %>
      <p>
      Folder is Empty
      <% if can? :create, @current_folder.class %>
      , you 
        <%= link_to 'can create new snippets', new_folder_snippet_path, class: 'text-red-700 underline' %>
      <% end %>
      </p>
    </div>
  <% else %>
    <ul class="p-4">
      <% @snippets.each do |snippet| %>
        <li class="mb-2">
          <div class="flex justify-between mb-2 items-center">
            <div>
              <%= snippet.name %>
              <span class="text-sm text-gray-500">
                <%= time_ago_in_words(snippet.updated_at) %> ago
              </span>
            </div>
            <div class="flex border rounded">
              <%# SEE CHANGES %>
              <% if snippet.versions.exists? && can?(:read, snippet.versions.klass) %>
                <%= link_to snippet_versions_path(snippet), class: 'flex items-center border-r px-2' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  <p class="text-sm">See Changes</p>
                <% end %>
              <% end %>
              <%# EMBED %>
              <% if can? :embed, snippet %>
                <button data-val="<%= snippet.id %>" class="embed-button flex items-center border-r px-2 text-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                  Embed
                </button>
              <% end %>
              <%# DOWNLOAD %>
              <% if can? :download, snippet %>
                <%= link_to download_path(snippet), class: 'flex items-center border-r px-2', target: '_blank' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  <p class="text-sm">Download</p>
                <% end %>
              <% end %>
              <%# EDIT %>
              <% if can? :edit, snippet %>
                <%= link_to edit_snippet_path(snippet), class: 'flex items-center border-r px-2' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                  <p class="text-sm">Edit</p>
                <% end %>
              <% end %>
              <%# DELETE %>
              <% if can? :destroy, snippet %>
                <%= link_to snippet_path(snippet), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure to delete #{snippet.name}"
                }, class: 'flex items-center px-2' do %>
                 <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
                <p class="text-sm">Delete</p>
                <% end %>
              <% end %>
            </div>
          </div>
          <%# content %>
          <pre class="rounded line-numbers">
            <code class="lang-<%= snippet.format %>">
              <%= snippet.content %>
            </code>
          </pre>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<%= content_for :additional_js do %>
  <%= javascript_include_tag "embed-button" %>
<% end %>

app/views/snippets/new.html.erb
<% content_for :sidebar do %>
  <%= render "folders/folder_lists", locals: {} %>
<% end %>

<% content_for :main_header do %> 
  <div class="p-4 border-b">
    <div>
      <h2 class="text-3xl font-bold mb-2">Write New Snippet</h2>
      <p class="text-lg mb-1">
        for 
        <%= link_to @folder.name, folder_snippets_path(@folder), class: 'text-red-700 underline' %> 
        folder
      </p>
    </div>
  </div>
<% end %>

<% content_for :main_content do %>
  <%= form_with model: [@folder, @snippet] do |form| %>
    <div class="flex flex-col border p-4 rounded">
      <div class="mb-2">
        <div class="flex items-center">
          <%= form.label :name, 'Snippet Name', class: 'text-gray-500 mr-2' %>
          <%= form.text_field :name, id: 'name-input', class: 'border-b' %>
        </div>
        <% @snippet.errors.full_messages_for(:name).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :content, class: 'hidden' %><br>
        <%# EDITOR %>
        <div id="editor" class="relative">
          <%= form.text_area :content, class: 'resize-none w-full overflow-hidden pl-16 p-5 text-white', style: 'font-family: "Andale Mono"; background: rgb(20, 20, 20);', id: 'snippet-input', placeholder: 'Input your code here' %>
          <pre class="w-full absolute rounded line-numbers top-0 left-0 pb-0 opacity-90" style="position:absolute; pointer-events: none; margin: 0; white-space: pre-wrap;">
            <code id="snippet-overlay" class=""></code>
          </pre>
        </div>
        <% @snippet.errors.full_messages_for(:content).each do |message| %>
          <p class="text-sm text-red-700">
            <%= message %>
          </p>
        <% end %>
      </div>
    
      <%= form.submit class: 'bg-green-400 rounded px-2 py-1 text-sm text-white self-end' %>
  <% end %>
<% end %>

<%= content_for :additional_js do %>
  <% if controller_name == 'snippets' && action_name == 'new' %>
    <%= javascript_include_tag "snippet-editor" %>
  <% end %>
<% end %>

app/views/snippets/show.html.erb
<h2>
  <%= @snippet.name %>
</h2>
<%= link_to 'see changes', snippet_versions_path(@snippet) %>
<p>
  from <%= @snippet.folder.name %> folder
</p>
<p>
  <%= @snippet.content %>
</p>