config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#landing"
  get '/404', to: 'pages#not_found', as: 'not_found'

  # uncomment this if you use custom controller in /controllers/users
  # devise_for :users, controllers: {
  #   confirmations: 'users/confirmations',
  #   passwords: 'users/passwords',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   unlocks: 'users/unlocks',
  # }
  devise_for :users
  
  resources :folders, except: [:show] do
    resources :snippets, only: [:index, :new, :create]
  end

  resources :snippets, only: [:edit, :update, :destroy] do
    resources :versions, only: :index
  end

  get '/snippets/:id/file', to: 'snippets#download', as: 'download' 
  get '/snippets/:id/embed', to: 'snippets#embed', as: 'embed' 
  get '/embed/script', to: 'snippets#embed_script' 
  get '/embed/style', to: 'snippets#embed_style' 
end

app/views/shared/_navbar.html.erb
<nav class="flex bg-red-700 p-4 justify-between items-center">
  <%= link_to "Symbolic-Snippet", root_path, class: 'text-white font-bold' %>
  <div class="flex items-center">
    <% unless user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class: 'mr-4 text-white' %>
      <%= link_to new_user_session_path, class: 'flex items-center rounded-full bg-white px-4 py-1' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
        </svg>
        <p>Sign In</p>
      <% end %>
    <% else %>
      <% if current_page?(root_path) %>
        <%= link_to "Open Dashboard", folder_snippets_path(current_user.folders.first), class: 'rounded-full bg-white px-4 py-1' %>
      <% else %>
        <%= link_to destroy_user_session_path, class: 'flex items-center' do %> 
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 stroke-white mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
          </svg>
          <p class="text-white">Logout</p>
        <% end %>
      <% end %>
    <% end %>
  </div>
</nav>